name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  Python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
          pip install -U pytest
          pip install flake8 black
          pip install mypy
          pip install coverage
          pip install pybind11
      - name: Build bazel
        run: .github/workflows/scripts/build_psi.sh
      - name: Run tests
        timeout-minutes: 15
        run: python -m pytest tests/
      - name: Python linters
        run: .github/workflows/scripts/lint_python.sh
  Docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Check Image Builds
      - run: docker build -t pyvertical:latest .
